[project]
name = "rfid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "flet[all]==0.28.3",
    "pillow>=12.1.0",
    "RPi.GPIO",
    "smbus2",
    "spidev>=3.8",
]
